workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.example.flutter1"
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Flutter build
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/**/*.aab
    publishing:
      # Configure publishing as needed
      # email:
      #   recipients:
      #     - your-email@example.com
      #   notify:
      #     success: true
      #     failure: true

