workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
        - apple_credentials
      vars:
        PACKAGE_NAME: "com.myneighborhood.app"
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android
        script: |
          flutter build appbundle --release
      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/app/outputs/bundle/**/*.aab
      - build/ios/ipa/*.ipa

code_signing:
  android-workflow:
    ios:
      distribution_type: development
      bundle_identifier: com.myneighborhood.app
      team_id: # Codemagic fills automatically after Apple Developer integration
