// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZH8y4mlSIXX_IsXe3I5ghLziRJp84TA',
    appId: '1:725875446445:web:a883dc3c1ebbdd960aec24',
    messagingSenderId: '725875446445',
    projectId: 'nearme-970f3',
    authDomain: 'nearme-970f3.firebaseapp.com',
    storageBucket: 'nearme-970f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhAEQ7wNaBH1nmtRs51WqZPGHfPoRtFQs',
    appId: '1:725875446445:android:1399519fbff5bf9b0aec24',
    messagingSenderId: '725875446445',
    projectId: 'nearme-970f3',
    storageBucket: 'nearme-970f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFkJPX4SoWmtxGkg65H2Y2fqPoenPau7c',
    appId: '1:725875446445:ios:540061ef8d3471190aec24',
    messagingSenderId: '725875446445',
    projectId: 'nearme-970f3',
    storageBucket: 'nearme-970f3.firebasestorage.app',
    iosBundleId: 'com.myneighborhood.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFkJPX4SoWmtxGkg65H2Y2fqPoenPau7c',
    appId: '1:725875446445:ios:540061ef8d3471190aec24',
    messagingSenderId: '725875446445',
    projectId: 'nearme-970f3',
    storageBucket: 'nearme-970f3.firebasestorage.app',
    iosBundleId: 'com.myneighborhood.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZH8y4mlSIXX_IsXe3I5ghLziRJp84TA',
    appId: '1:725875446445:web:a883dc3c1ebbdd960aec24',
    messagingSenderId: '725875446445',
    projectId: 'nearme-970f3',
    authDomain: 'nearme-970f3.firebaseapp.com',
    storageBucket: 'nearme-970f3.firebasestorage.app',
  );
}